name = "weatherscan"
compatibility_date = "2026-04-11"

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = true

[observability]
[observability.logs]
enabled = true
invocation_logs = true
